services:
  - name: transaction-web-app
    type: web
    env: docker
    buildCommand: 'docker build -t transaction-web-app .'  # Build Docker image
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: starter  # Or another plan depending on your needs
    region: oregon  # Set the region where you want to deploy
