services:
  - name: transaction-web-app
    type: web
    env: aspnet
    buildCommand: 'dotnet publish -c Release -o /app'
    startCommand: 'dotnet /app/TransactionWebApp.dll'
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: free  # Or a paid plan depending on your needs
    region: oregon
