version: 1
services:
  - name: transaction-web-app
    type: web
    env: static
    buildCommand: 'dotnet publish -c Release -o /app'
    startCommand: 'dotnet /app/TransactionWebApp.dll'
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    plan: starter  # You can change this to 'standard' or 'pro' for higher plans
    region: oregon  # You can specify other regions as needed
